### ISSUE TITLE
Uses of CON_TELL and w4rn/w4rn_message

### ISSUE THREAD

**Issue by Kekmeister** [opnsrce/hackmud#34]
`CON_TELL` and `w4rn` are both currently cited as locks that exist to eat up the execution time of the attacker's cracker script. For `CON_TELL` it's true; Although its advertised use is early-warning that a human or the chat API can use to trigger a response, anyone can fake a `CON_TELL` tell to provoke a botnet, or poke your loc to spam you with tells, so when it is used, it is typically used for the rather slow exeuction time of chats.tell at 30ms, since it has to travel through a lot of bullshit to actually send a chat message.

`w4rn` however does not eat up much time at all -- it only adds a couple of lines of text above whatever else the loc may be returning before returning it to the caller. 
Originally this had no real limits, so you can thank the veterans for abusing it into the ground with client crash messages and hundreds of linebreaks because as it stands now there is a _**100 character limit**_ on the message you can set for `w4rn` using the `w4rn_message` upgrade. 

This is best used in feigning loc(k) return messages in attempt to make the cracker trying to crack your loc fail -- but it's a weak attempt at it, because crackers can avoid ever reading what w4rn prepends to the locs return in pretty much every case.
For instance:

- \`VLOCK_ERROR\`\nDenied access by sn_w inc \`Nsn_w_glock\` lock.
- \`VLOCK_UNLOCKED\`\nConnection Terminated.

Are two examples of a `w4rn` message that might make a bad cracker peace out, but it could simply read only the lines of a loc's return it knows it can trust, like the last line, as all locs will return at least one line of text in all cases, and read more only when you know you can trust more, like when reading out DATA_CHECK questions, where you know the last three lines are trustworthy.

It still is worth adding to your lockstack if you have no lock you could put in there instead, if you just want to insult your attacker, or if you just want it to shitpost, but it is not "viable" against anyone seriously trying to crack your loc.

**Comment by opnsrce** [comment]
This is great information. Thanks for clarifying what those upgrades do, I had a hell of a time figuring it out on my own (as you can see).

I'll get the guide updated.
